dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install .
script:
  - echo -e "${ANSI_GREEN}Running Tests...${ANSI_RESET}" && echo -en 'travis_fold:start:tests\\r'
  - python -m unittest discover
  - echo -en 'travis_fold:end:tests\\r'
