dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install .
  - pip install coverage
script:
  - echo -e "${ANSI_GREEN}Running Tests...${ANSI_RESET}" 
  - travis_fold:start:tests
  - coverage run -m unittest --v
  - travis_fold:end:tests
after_success:
  - bash <(curl -s https://codecov.io/bash)